### ISSUE TITLE
Prompt missing parannoid_ Pd2 cannot be imported

### ISSUE THREAD

**Issue by rjfrjf** [google/paranoid_crypto#13]
Prompt missing parannoid_ Pd2 cannot be imported
Request guidance！
thanks！
![微信图片_20220922083630](https://user-images.githubusercontent.com/76422270/191633628-e58667b3-2a14-4db9-b55b-b0901ad6ff2c.jpg)

**Comment by pedroysb** [comment]
Hi,

paranoid_pb2 is compiled in setup.py when you install the python package. So it seems to me you are trying to run it before installing the package.

Please make sure you follow the steps at https://github.com/google/paranoid_crypto#installation
