### ISSUE TITLE
When deploying to pycharm, an error is reported and help is sought

### ISSUE THREAD

**Issue by rjfrjf** [google/paranoid_crypto#15]
When deploying to pycharm, an error is reported and help is sought
<img width="996" alt="WechatIMG1" src="https://user-images.githubusercontent.com/76422270/193447528-d9f5f222-00a3-4cb3-b93c-71e01eee3f21.png">
![31664702290_ pic](https://user-images.githubusercontent.com/76422270/193447534-7fcdb456-b6f8-490d-9f1a-8a124da48f29.jpg)
![41664702313_ pic](https://user-images.githubusercontent.com/76422270/193447535-34276822-fafa-4dc3-b6da-62e8eed4e052.jpg)
![51664702334_ pic](https://user-images.githubusercontent.com/76422270/193447536-74436327-c85f-477b-91e1-a692a8a52930.jpg)
![61664702354_ pic](https://user-images.githubusercontent.com/76422270/193447539-331f1681-1040-453e-80ad-d934b43a3d00.jpg)
![71664702374_ pic](https://user-images.githubusercontent.com/76422270/193447540-3d3fb36b-65ae-46fc-99dd-2f1eec11c2da.jpg)

**Comment by pedroysb** [comment]
It seems to me you are trying to install paranoid_crypto without installing its dependencies first. Make sure you follow the instructions at https://github.com/google/paranoid_crypto#installation, including the `sudo apt install libgmp-dev` part.

If you are using Mac, a possibility is to use docker: https://github.com/google/paranoid_crypto#docker
